version: '3'
services:
  beverage:
    build: Beverage-Service

    ports:
      - "8080:8080"
    networks:
      - a-net
    depends_on:
      - "db"
  management:
    build: Management-Service

    ports:
      - "8090:8090"
    networks:
      - a-net
    depends_on:
      - "db"

  db:
    build: DB-Handler
    networks:
      - a-net

networks:
  a-net:
    driver: bridge
